version: '3.9'
services:
  prism:
    image: stoplight/prism:4 
    command: 'mock -h 0.0.0.0 /tmp/TMT.yaml'
    volumes:
      - ./openapi/TMT.yaml:/tmp/TMT.yaml
    ports:
      - '4010:4010'
  tmt-productizer:
    build: .
    ports:
      - '5286:5286'
    depends_on:
      - prism
    environment:
      - TmtOptions__ApiEndpoint=http://prism:4010/api/v1/tyopaikat
      - ASPNETCORE_URLS=http://localhost:5286