/*
 * TMT - Työpaikkailmoituksien hakurajapinta | Get Job postings
 *
 * <p>Tämän rajapinnan avulla voit hakea kaikki Työmarkkinatorilla julkaistut työpaikkailmoitukset.</p> <p>With this rest interface, you can retrieve all Job postings published in Job market Finland.</p>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CodeGen.Api.TMT.Client.OpenAPIDateConverter;

namespace CodeGen.Api.TMT.Model
{
    /// <summary>
    /// **fi:** Lokalisoidulla arvolla on kielikoodi sekä arvo | **en:** Localized value has language code and value of that language
    /// </summary>
    [DataContract(Name = "LokalisoituArvo")]
    public partial class LokalisoituArvo : IEquatable<LokalisoituArvo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LokalisoituArvo" /> class.
        /// </summary>
        /// <param name="arvo">**fi:** Tekstiarvo | **en:** Value.</param>
        /// <param name="kieliKoodi">**fi:** Kielikoodi (fi, sv, en) | **en:** Language code (fi, sv, en).</param>
        public LokalisoituArvo(string arvo = default(string), string kieliKoodi = default(string))
        {
            this.Arvo = arvo;
            this.KieliKoodi = kieliKoodi;
        }

        /// <summary>
        /// **fi:** Tekstiarvo | **en:** Value
        /// </summary>
        /// <value>**fi:** Tekstiarvo | **en:** Value</value>
        [DataMember(Name = "arvo", EmitDefaultValue = false)]
        public string Arvo { get; set; }

        /// <summary>
        /// **fi:** Kielikoodi (fi, sv, en) | **en:** Language code (fi, sv, en)
        /// </summary>
        /// <value>**fi:** Kielikoodi (fi, sv, en) | **en:** Language code (fi, sv, en)</value>
        [DataMember(Name = "kieliKoodi", EmitDefaultValue = false)]
        public string KieliKoodi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LokalisoituArvo {\n");
            sb.Append("  Arvo: ").Append(Arvo).Append("\n");
            sb.Append("  KieliKoodi: ").Append(KieliKoodi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LokalisoituArvo);
        }

        /// <summary>
        /// Returns true if LokalisoituArvo instances are equal
        /// </summary>
        /// <param name="input">Instance of LokalisoituArvo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LokalisoituArvo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Arvo == input.Arvo ||
                    (this.Arvo != null &&
                    this.Arvo.Equals(input.Arvo))
                ) && 
                (
                    this.KieliKoodi == input.KieliKoodi ||
                    (this.KieliKoodi != null &&
                    this.KieliKoodi.Equals(input.KieliKoodi))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Arvo != null)
                {
                    hashCode = (hashCode * 59) + this.Arvo.GetHashCode();
                }
                if (this.KieliKoodi != null)
                {
                    hashCode = (hashCode * 59) + this.KieliKoodi.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
