/*
 * TMT - Työpaikkailmoituksien hakurajapinta | Get Job postings
 *
 * <p>Tämän rajapinnan avulla voit hakea kaikki Työmarkkinatorilla julkaistut työpaikkailmoitukset.</p> <p>With this rest interface, you can retrieve all Job postings published in Job market Finland.</p>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CodeGen.Api.TMT.Client.OpenAPIDateConverter;

namespace CodeGen.Api.TMT.Model
{
    /// <summary>
    /// **fi:** Työpaikkailmoituksen perustiedot | **en:** Basic information of the job posting
    /// </summary>
    [DataContract(Name = "Perustiedot")]
    public partial class Perustiedot : IEquatable<Perustiedot>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Perustiedot" /> class.
        /// </summary>
        /// <param name="kutsutaanTarvittaessa">**fi:** Kutstutaan töihin tarvittaessa | **en:** To be called when needed.</param>
        /// <param name="kuuluuMatkustamista">**fi:** Työhön kuuluu matkustamista | **en:** The job involves travel.</param>
        /// <param name="maaraaikaisuudenPaattymisPvm">**fi:** Määräaikausuuden päättymispäivä | **en:** Employment relationship end date for temporary contract.</param>
        /// <param name="maaraaikaisuudenSyy">**fi:** Määräaikaisuuden syy | **en:** Reason for temporary employment relationship.</param>
        /// <param name="paikkojenMaara">**fi:** Työpaikkailmoituksen avoimien paikkojen kokonaismäärä | **en:** Quantity of open positions.</param>
        /// <param name="palkanLisatieto">**fi:** Palkan lisätieto | **en:** Additional information on wage principle.</param>
        /// <param name="palkanPeruste">**fi:** Palkanperuste | **en:** Principle of wage&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Aikapalkka | Time rate 02 &#x3D; Kiinteä palkka | Fixed salary 03 &#x3D; Provisiopalkka | Bonus-based 04 &#x3D; Kiinteä palkka + provisio | Fixed salary + bonus 05 &#x3D; Aikapalkka + provisio | Time rate + bonus 06 &#x3D; Urakkapalkka | Piece work pay 07 &#x3D; Muu | Other&lt;/pre&gt;&lt;/details&gt;.</param>
        /// <param name="tyoAika">**fi:** Työaika | **en:** Type of work time&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Kokoaikatyö | Full-time  02 &#x3D; Osa-aikatyö | Part-time&lt;/pre&gt;.</param>
        /// <param name="tyoAlkaa">**fi:** Työn alkamisen tyyppi | **en:** Type of start of work&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Mahdollisimman pian | As soon as possible 02 &#x3D; Alkaen | Starting on 03 &#x3D; Sopimuksen mukaan | According to agreement&lt;/pre&gt;&lt;/details&gt;.</param>
        /// <param name="tyoAlkaaLisatieto">**fi:** Työn aloituksen lisätieto | **en:** Additional information on start of work.</param>
        /// <param name="tyoAlkaaPvm">**fi:** Työn aloitus, vain jos tyo alkaa tyyppi on &#39;*02*&#39; | **en:**  Work start date (field has value only if start of work type is &#39;*02*&#39;).</param>
        /// <param name="tyoTunnitAjanjakso">**fi:** Osa-aikaisen työn tuntien ajanjakso | **en:** Part time working hours&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;0201 &#x3D; Osa-aikatyö, tuntia viikossa | Part-time, hours per week 0202 &#x3D; Osa-aikatyö, tuntia kuukaudessa | part-time, hours per month&lt;/pre&gt;&lt;/details&gt;.</param>
        /// <param name="tyoTunnitMaksimi">*fi:** Osa-aikaisen työsuhteen työtunteja enintään | *en:** Maximum amount of working hours for part-time work.</param>
        /// <param name="tyoTunnitMinimi">*fi:** Osa-aikaisen työsuhteen työtunteja vähintään | **en:** Minimum amount of working hours for part-time work.</param>
        /// <param name="tyonJatkuvuus">**fi:** Työn jatkuvuus | **en:** Type of employment contract&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Toistaiseksi voimassa oleva | Permanent 02 &#x3D; Määräaikainen | Temporary 0201 &#x3D; Kausityö | Seasonal work 0202 &#x3D; Kesätyö | Summer work&lt;/pre&gt;&lt;/details&gt;.</param>
        /// <param name="tyonKuvaus">**fi:**Työpaikkailmoituksen kuvaus | **en:** Description of the job posting.</param>
        /// <param name="tyonOtsikko">**fi:** Työpaikkailmoituksen otsikko | **en:** Title of the job posting.</param>
        /// <param name="tyonTiivistelma">**fi:** Työpaikkailmoituksen kuvauksen tiivistelmä | **en:** Short description of the job posting.</param>
        /// <param name="tyoskentely">tyoskentely.</param>
        public Perustiedot(bool kutsutaanTarvittaessa = default(bool), bool kuuluuMatkustamista = default(bool), DateTime maaraaikaisuudenPaattymisPvm = default(DateTime), List<LokalisoituArvo> maaraaikaisuudenSyy = default(List<LokalisoituArvo>), int paikkojenMaara = default(int), List<LokalisoituArvo> palkanLisatieto = default(List<LokalisoituArvo>), string palkanPeruste = default(string), /*Palvelussuhde palvelussuhde = default(Palvelussuhde),*/ string tyoAika = default(string), string tyoAlkaa = default(string), List<LokalisoituArvo> tyoAlkaaLisatieto = default(List<LokalisoituArvo>), DateTime tyoAlkaaPvm = default(DateTime), string tyoTunnitAjanjakso = default(string), double tyoTunnitMaksimi = default(double), double tyoTunnitMinimi = default(double), string tyonJatkuvuus = default(string), List<LokalisoituArvo> tyonKuvaus = default(List<LokalisoituArvo>), List<LokalisoituArvo> tyonOtsikko = default(List<LokalisoituArvo>), List<LokalisoituArvo> tyonTiivistelma = default(List<LokalisoituArvo>), Tyoskentely tyoskentely = default(Tyoskentely))
        {
            this.KutsutaanTarvittaessa = kutsutaanTarvittaessa;
            this.KuuluuMatkustamista = kuuluuMatkustamista;
            this.MaaraaikaisuudenPaattymisPvm = maaraaikaisuudenPaattymisPvm;
            this.MaaraaikaisuudenSyy = maaraaikaisuudenSyy;
            this.PaikkojenMaara = paikkojenMaara;
            this.PalkanLisatieto = palkanLisatieto;
            this.PalkanPeruste = palkanPeruste;
            //this.Palvelussuhde = palvelussuhde;
            this.TyoAika = tyoAika;
            this.TyoAlkaa = tyoAlkaa;
            this.TyoAlkaaLisatieto = tyoAlkaaLisatieto;
            this.TyoAlkaaPvm = tyoAlkaaPvm;
            this.TyoTunnitAjanjakso = tyoTunnitAjanjakso;
            this.TyoTunnitMaksimi = tyoTunnitMaksimi;
            this.TyoTunnitMinimi = tyoTunnitMinimi;
            this.TyonJatkuvuus = tyonJatkuvuus;
            this.TyonKuvaus = tyonKuvaus;
            this.TyonOtsikko = tyonOtsikko;
            this.TyonTiivistelma = tyonTiivistelma;
            this.Tyoskentely = tyoskentely;
        }

        /// <summary>
        /// **fi:** Kutstutaan töihin tarvittaessa | **en:** To be called when needed
        /// </summary>
        /// <value>**fi:** Kutstutaan töihin tarvittaessa | **en:** To be called when needed</value>
        [DataMember(Name = "kutsutaanTarvittaessa", EmitDefaultValue = true)]
        public bool KutsutaanTarvittaessa { get; set; }

        /// <summary>
        /// **fi:** Työhön kuuluu matkustamista | **en:** The job involves travel
        /// </summary>
        /// <value>**fi:** Työhön kuuluu matkustamista | **en:** The job involves travel</value>
        [DataMember(Name = "kuuluuMatkustamista", EmitDefaultValue = true)]
        public bool KuuluuMatkustamista { get; set; }

        /// <summary>
        /// **fi:** Määräaikausuuden päättymispäivä | **en:** Employment relationship end date for temporary contract
        /// </summary>
        /// <value>**fi:** Määräaikausuuden päättymispäivä | **en:** Employment relationship end date for temporary contract</value>
        [DataMember(Name = "maaraaikaisuudenPaattymisPvm", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime MaaraaikaisuudenPaattymisPvm { get; set; }

        /// <summary>
        /// **fi:** Määräaikaisuuden syy | **en:** Reason for temporary employment relationship
        /// </summary>
        /// <value>**fi:** Määräaikaisuuden syy | **en:** Reason for temporary employment relationship</value>
        [DataMember(Name = "maaraaikaisuudenSyy", EmitDefaultValue = false)]
        public List<LokalisoituArvo> MaaraaikaisuudenSyy { get; set; }

        /// <summary>
        /// **fi:** Työpaikkailmoituksen avoimien paikkojen kokonaismäärä | **en:** Quantity of open positions
        /// </summary>
        /// <value>**fi:** Työpaikkailmoituksen avoimien paikkojen kokonaismäärä | **en:** Quantity of open positions</value>
        [DataMember(Name = "paikkojenMaara", EmitDefaultValue = false)]
        public int PaikkojenMaara { get; set; }

        /// <summary>
        /// **fi:** Palkan lisätieto | **en:** Additional information on wage principle
        /// </summary>
        /// <value>**fi:** Palkan lisätieto | **en:** Additional information on wage principle</value>
        [DataMember(Name = "palkanLisatieto", EmitDefaultValue = false)]
        public List<LokalisoituArvo> PalkanLisatieto { get; set; }

        /// <summary>
        /// **fi:** Palkanperuste | **en:** Principle of wage&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Aikapalkka | Time rate 02 &#x3D; Kiinteä palkka | Fixed salary 03 &#x3D; Provisiopalkka | Bonus-based 04 &#x3D; Kiinteä palkka + provisio | Fixed salary + bonus 05 &#x3D; Aikapalkka + provisio | Time rate + bonus 06 &#x3D; Urakkapalkka | Piece work pay 07 &#x3D; Muu | Other&lt;/pre&gt;&lt;/details&gt;
        /// </summary>
        /// <value>**fi:** Palkanperuste | **en:** Principle of wage&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Aikapalkka | Time rate 02 &#x3D; Kiinteä palkka | Fixed salary 03 &#x3D; Provisiopalkka | Bonus-based 04 &#x3D; Kiinteä palkka + provisio | Fixed salary + bonus 05 &#x3D; Aikapalkka + provisio | Time rate + bonus 06 &#x3D; Urakkapalkka | Piece work pay 07 &#x3D; Muu | Other&lt;/pre&gt;&lt;/details&gt;</value>
        [DataMember(Name = "palkanPeruste", EmitDefaultValue = false)]
        public string PalkanPeruste { get; set; }

        /// <summary>
        /// Gets or Sets Palvelussuhde
        /// </summary>
        //[DataMember(Name = "palvelussuhde", EmitDefaultValue = false)]
        //public Palvelussuhde Palvelussuhde { get; set; }

        /// <summary>
        /// **fi:** Työaika | **en:** Type of work time&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Kokoaikatyö | Full-time  02 &#x3D; Osa-aikatyö | Part-time&lt;/pre&gt;
        /// </summary>
        /// <value>**fi:** Työaika | **en:** Type of work time&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Kokoaikatyö | Full-time  02 &#x3D; Osa-aikatyö | Part-time&lt;/pre&gt;</value>
        [DataMember(Name = "tyoAika", EmitDefaultValue = false)]
        public string TyoAika { get; set; }

        /// <summary>
        /// **fi:** Työn alkamisen tyyppi | **en:** Type of start of work&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Mahdollisimman pian | As soon as possible 02 &#x3D; Alkaen | Starting on 03 &#x3D; Sopimuksen mukaan | According to agreement&lt;/pre&gt;&lt;/details&gt;
        /// </summary>
        /// <value>**fi:** Työn alkamisen tyyppi | **en:** Type of start of work&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Mahdollisimman pian | As soon as possible 02 &#x3D; Alkaen | Starting on 03 &#x3D; Sopimuksen mukaan | According to agreement&lt;/pre&gt;&lt;/details&gt;</value>
        [DataMember(Name = "tyoAlkaa", EmitDefaultValue = false)]
        public string TyoAlkaa { get; set; }

        /// <summary>
        /// **fi:** Työn aloituksen lisätieto | **en:** Additional information on start of work
        /// </summary>
        /// <value>**fi:** Työn aloituksen lisätieto | **en:** Additional information on start of work</value>
        [DataMember(Name = "tyoAlkaaLisatieto", EmitDefaultValue = false)]
        public List<LokalisoituArvo> TyoAlkaaLisatieto { get; set; }

        /// <summary>
        /// **fi:** Työn aloitus, vain jos tyo alkaa tyyppi on &#39;*02*&#39; | **en:**  Work start date (field has value only if start of work type is &#39;*02*&#39;)
        /// </summary>
        /// <value>**fi:** Työn aloitus, vain jos tyo alkaa tyyppi on &#39;*02*&#39; | **en:**  Work start date (field has value only if start of work type is &#39;*02*&#39;)</value>
        [DataMember(Name = "tyoAlkaaPvm", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime TyoAlkaaPvm { get; set; }

        /// <summary>
        /// **fi:** Osa-aikaisen työn tuntien ajanjakso | **en:** Part time working hours&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;0201 &#x3D; Osa-aikatyö, tuntia viikossa | Part-time, hours per week 0202 &#x3D; Osa-aikatyö, tuntia kuukaudessa | part-time, hours per month&lt;/pre&gt;&lt;/details&gt;
        /// </summary>
        /// <value>**fi:** Osa-aikaisen työn tuntien ajanjakso | **en:** Part time working hours&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;0201 &#x3D; Osa-aikatyö, tuntia viikossa | Part-time, hours per week 0202 &#x3D; Osa-aikatyö, tuntia kuukaudessa | part-time, hours per month&lt;/pre&gt;&lt;/details&gt;</value>
        [DataMember(Name = "tyoTunnitAjanjakso", EmitDefaultValue = false)]
        public string TyoTunnitAjanjakso { get; set; }

        /// <summary>
        /// *fi:** Osa-aikaisen työsuhteen työtunteja enintään | *en:** Maximum amount of working hours for part-time work
        /// </summary>
        /// <value>*fi:** Osa-aikaisen työsuhteen työtunteja enintään | *en:** Maximum amount of working hours for part-time work</value>
        [DataMember(Name = "tyoTunnitMaksimi", EmitDefaultValue = false)]
        public double TyoTunnitMaksimi { get; set; }

        /// <summary>
        /// *fi:** Osa-aikaisen työsuhteen työtunteja vähintään | **en:** Minimum amount of working hours for part-time work
        /// </summary>
        /// <value>*fi:** Osa-aikaisen työsuhteen työtunteja vähintään | **en:** Minimum amount of working hours for part-time work</value>
        [DataMember(Name = "tyoTunnitMinimi", EmitDefaultValue = false)]
        public double TyoTunnitMinimi { get; set; }

        /// <summary>
        /// **fi:** Työn jatkuvuus | **en:** Type of employment contract&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Toistaiseksi voimassa oleva | Permanent 02 &#x3D; Määräaikainen | Temporary 0201 &#x3D; Kausityö | Seasonal work 0202 &#x3D; Kesätyö | Summer work&lt;/pre&gt;&lt;/details&gt;
        /// </summary>
        /// <value>**fi:** Työn jatkuvuus | **en:** Type of employment contract&lt;details&gt;&lt;summary&gt;Koodit | Codes&lt;/summary&gt;&lt;pre&gt;01 &#x3D; Toistaiseksi voimassa oleva | Permanent 02 &#x3D; Määräaikainen | Temporary 0201 &#x3D; Kausityö | Seasonal work 0202 &#x3D; Kesätyö | Summer work&lt;/pre&gt;&lt;/details&gt;</value>
        [DataMember(Name = "tyonJatkuvuus", EmitDefaultValue = false)]
        public string TyonJatkuvuus { get; set; }

        /// <summary>
        /// **fi:**Työpaikkailmoituksen kuvaus | **en:** Description of the job posting
        /// </summary>
        /// <value>**fi:**Työpaikkailmoituksen kuvaus | **en:** Description of the job posting</value>
        [DataMember(Name = "tyonKuvaus", EmitDefaultValue = false)]
        public List<LokalisoituArvo> TyonKuvaus { get; set; }

        /// <summary>
        /// **fi:** Työpaikkailmoituksen otsikko | **en:** Title of the job posting
        /// </summary>
        /// <value>**fi:** Työpaikkailmoituksen otsikko | **en:** Title of the job posting</value>
        [DataMember(Name = "tyonOtsikko", EmitDefaultValue = false)]
        public List<LokalisoituArvo> TyonOtsikko { get; set; }

        /// <summary>
        /// **fi:** Työpaikkailmoituksen kuvauksen tiivistelmä | **en:** Short description of the job posting
        /// </summary>
        /// <value>**fi:** Työpaikkailmoituksen kuvauksen tiivistelmä | **en:** Short description of the job posting</value>
        [DataMember(Name = "tyonTiivistelma", EmitDefaultValue = false)]
        public List<LokalisoituArvo> TyonTiivistelma { get; set; }

        /// <summary>
        /// Gets or Sets Tyoskentely
        /// </summary>
        [DataMember(Name = "tyoskentely", EmitDefaultValue = false)]
        public Tyoskentely Tyoskentely { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Perustiedot {\n");
            sb.Append("  KutsutaanTarvittaessa: ").Append(KutsutaanTarvittaessa).Append("\n");
            sb.Append("  KuuluuMatkustamista: ").Append(KuuluuMatkustamista).Append("\n");
            sb.Append("  MaaraaikaisuudenPaattymisPvm: ").Append(MaaraaikaisuudenPaattymisPvm).Append("\n");
            sb.Append("  MaaraaikaisuudenSyy: ").Append(MaaraaikaisuudenSyy).Append("\n");
            sb.Append("  PaikkojenMaara: ").Append(PaikkojenMaara).Append("\n");
            sb.Append("  PalkanLisatieto: ").Append(PalkanLisatieto).Append("\n");
            sb.Append("  PalkanPeruste: ").Append(PalkanPeruste).Append("\n");
            //sb.Append("  Palvelussuhde: ").Append(Palvelussuhde).Append("\n");
            sb.Append("  TyoAika: ").Append(TyoAika).Append("\n");
            sb.Append("  TyoAlkaa: ").Append(TyoAlkaa).Append("\n");
            sb.Append("  TyoAlkaaLisatieto: ").Append(TyoAlkaaLisatieto).Append("\n");
            sb.Append("  TyoAlkaaPvm: ").Append(TyoAlkaaPvm).Append("\n");
            sb.Append("  TyoTunnitAjanjakso: ").Append(TyoTunnitAjanjakso).Append("\n");
            sb.Append("  TyoTunnitMaksimi: ").Append(TyoTunnitMaksimi).Append("\n");
            sb.Append("  TyoTunnitMinimi: ").Append(TyoTunnitMinimi).Append("\n");
            sb.Append("  TyonJatkuvuus: ").Append(TyonJatkuvuus).Append("\n");
            sb.Append("  TyonKuvaus: ").Append(TyonKuvaus).Append("\n");
            sb.Append("  TyonOtsikko: ").Append(TyonOtsikko).Append("\n");
            sb.Append("  TyonTiivistelma: ").Append(TyonTiivistelma).Append("\n");
            sb.Append("  Tyoskentely: ").Append(Tyoskentely).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Perustiedot);
        }

        /// <summary>
        /// Returns true if Perustiedot instances are equal
        /// </summary>
        /// <param name="input">Instance of Perustiedot to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Perustiedot input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.KutsutaanTarvittaessa == input.KutsutaanTarvittaessa ||
                    this.KutsutaanTarvittaessa.Equals(input.KutsutaanTarvittaessa)
                ) &&
                (
                    this.KuuluuMatkustamista == input.KuuluuMatkustamista ||
                    this.KuuluuMatkustamista.Equals(input.KuuluuMatkustamista)
                ) &&
                (
                    this.MaaraaikaisuudenPaattymisPvm == input.MaaraaikaisuudenPaattymisPvm ||
                    (this.MaaraaikaisuudenPaattymisPvm != null &&
                    this.MaaraaikaisuudenPaattymisPvm.Equals(input.MaaraaikaisuudenPaattymisPvm))
                ) &&
                (
                    this.MaaraaikaisuudenSyy == input.MaaraaikaisuudenSyy ||
                    this.MaaraaikaisuudenSyy != null &&
                    input.MaaraaikaisuudenSyy != null &&
                    this.MaaraaikaisuudenSyy.SequenceEqual(input.MaaraaikaisuudenSyy)
                ) &&
                (
                    this.PaikkojenMaara == input.PaikkojenMaara ||
                    this.PaikkojenMaara.Equals(input.PaikkojenMaara)
                ) &&
                (
                    this.PalkanLisatieto == input.PalkanLisatieto ||
                    this.PalkanLisatieto != null &&
                    input.PalkanLisatieto != null &&
                    this.PalkanLisatieto.SequenceEqual(input.PalkanLisatieto)
                ) &&
                (
                    this.PalkanPeruste == input.PalkanPeruste ||
                    (this.PalkanPeruste != null &&
                    this.PalkanPeruste.Equals(input.PalkanPeruste))
                ) &&
                /*  (
                     this.Palvelussuhde == input.Palvelussuhde ||
                     (this.Palvelussuhde != null &&
                     this.Palvelussuhde.Equals(input.Palvelussuhde))
                 ) && */
                (
                    this.TyoAika == input.TyoAika ||
                    (this.TyoAika != null &&
                    this.TyoAika.Equals(input.TyoAika))
                ) &&
                (
                    this.TyoAlkaa == input.TyoAlkaa ||
                    (this.TyoAlkaa != null &&
                    this.TyoAlkaa.Equals(input.TyoAlkaa))
                ) &&
                (
                    this.TyoAlkaaLisatieto == input.TyoAlkaaLisatieto ||
                    this.TyoAlkaaLisatieto != null &&
                    input.TyoAlkaaLisatieto != null &&
                    this.TyoAlkaaLisatieto.SequenceEqual(input.TyoAlkaaLisatieto)
                ) &&
                (
                    this.TyoAlkaaPvm == input.TyoAlkaaPvm ||
                    (this.TyoAlkaaPvm != null &&
                    this.TyoAlkaaPvm.Equals(input.TyoAlkaaPvm))
                ) &&
                (
                    this.TyoTunnitAjanjakso == input.TyoTunnitAjanjakso ||
                    (this.TyoTunnitAjanjakso != null &&
                    this.TyoTunnitAjanjakso.Equals(input.TyoTunnitAjanjakso))
                ) &&
                (
                    this.TyoTunnitMaksimi == input.TyoTunnitMaksimi ||
                    this.TyoTunnitMaksimi.Equals(input.TyoTunnitMaksimi)
                ) &&
                (
                    this.TyoTunnitMinimi == input.TyoTunnitMinimi ||
                    this.TyoTunnitMinimi.Equals(input.TyoTunnitMinimi)
                ) &&
                (
                    this.TyonJatkuvuus == input.TyonJatkuvuus ||
                    (this.TyonJatkuvuus != null &&
                    this.TyonJatkuvuus.Equals(input.TyonJatkuvuus))
                ) &&
                (
                    this.TyonKuvaus == input.TyonKuvaus ||
                    this.TyonKuvaus != null &&
                    input.TyonKuvaus != null &&
                    this.TyonKuvaus.SequenceEqual(input.TyonKuvaus)
                ) &&
                (
                    this.TyonOtsikko == input.TyonOtsikko ||
                    this.TyonOtsikko != null &&
                    input.TyonOtsikko != null &&
                    this.TyonOtsikko.SequenceEqual(input.TyonOtsikko)
                ) &&
                (
                    this.TyonTiivistelma == input.TyonTiivistelma ||
                    this.TyonTiivistelma != null &&
                    input.TyonTiivistelma != null &&
                    this.TyonTiivistelma.SequenceEqual(input.TyonTiivistelma)
                ) &&
                (
                    this.Tyoskentely == input.Tyoskentely ||
                    (this.Tyoskentely != null &&
                    this.Tyoskentely.Equals(input.Tyoskentely))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.KutsutaanTarvittaessa.GetHashCode();
                hashCode = (hashCode * 59) + this.KuuluuMatkustamista.GetHashCode();
                if (this.MaaraaikaisuudenPaattymisPvm != null)
                {
                    hashCode = (hashCode * 59) + this.MaaraaikaisuudenPaattymisPvm.GetHashCode();
                }
                if (this.MaaraaikaisuudenSyy != null)
                {
                    hashCode = (hashCode * 59) + this.MaaraaikaisuudenSyy.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.PaikkojenMaara.GetHashCode();
                if (this.PalkanLisatieto != null)
                {
                    hashCode = (hashCode * 59) + this.PalkanLisatieto.GetHashCode();
                }
                if (this.PalkanPeruste != null)
                {
                    hashCode = (hashCode * 59) + this.PalkanPeruste.GetHashCode();
                }
                /* if (this.Palvelussuhde != null)
                {
                    hashCode = (hashCode * 59) + this.Palvelussuhde.GetHashCode();
                } */
                if (this.TyoAika != null)
                {
                    hashCode = (hashCode * 59) + this.TyoAika.GetHashCode();
                }
                if (this.TyoAlkaa != null)
                {
                    hashCode = (hashCode * 59) + this.TyoAlkaa.GetHashCode();
                }
                if (this.TyoAlkaaLisatieto != null)
                {
                    hashCode = (hashCode * 59) + this.TyoAlkaaLisatieto.GetHashCode();
                }
                if (this.TyoAlkaaPvm != null)
                {
                    hashCode = (hashCode * 59) + this.TyoAlkaaPvm.GetHashCode();
                }
                if (this.TyoTunnitAjanjakso != null)
                {
                    hashCode = (hashCode * 59) + this.TyoTunnitAjanjakso.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TyoTunnitMaksimi.GetHashCode();
                hashCode = (hashCode * 59) + this.TyoTunnitMinimi.GetHashCode();
                if (this.TyonJatkuvuus != null)
                {
                    hashCode = (hashCode * 59) + this.TyonJatkuvuus.GetHashCode();
                }
                if (this.TyonKuvaus != null)
                {
                    hashCode = (hashCode * 59) + this.TyonKuvaus.GetHashCode();
                }
                if (this.TyonOtsikko != null)
                {
                    hashCode = (hashCode * 59) + this.TyonOtsikko.GetHashCode();
                }
                if (this.TyonTiivistelma != null)
                {
                    hashCode = (hashCode * 59) + this.TyonTiivistelma.GetHashCode();
                }
                if (this.Tyoskentely != null)
                {
                    hashCode = (hashCode * 59) + this.Tyoskentely.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
