/*
 * TMT - Työpaikkailmoituksien hakurajapinta | Get Job postings
 *
 * <p>Tämän rajapinnan avulla voit hakea kaikki Työmarkkinatorilla julkaistut työpaikkailmoitukset.</p> <p>With this rest interface, you can retrieve all Job postings published in Job market Finland.</p>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CodeGen.Api.TMT.Client.OpenAPIDateConverter;

namespace CodeGen.Api.TMT.Model
{
    /// <summary>
    /// **fi:** Sivutustiedot | **en:** Paging information 
    /// </summary>
    [DataContract(Name = "Sivutus")]
    public partial class Sivutus : IEquatable<Sivutus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Sivutus" /> class.
        /// </summary>
        /// <param name="maara">**fi:** Pyydetty määrä per sivu | **en:** Requested amount of job postings.</param>
        /// <param name="sivu">**fi:** Sivun numero | **en:** Page number.</param>
        public Sivutus(int maara = default(int), int sivu = default(int))
        {
            this.Maara = maara;
            this.Sivu = sivu;
        }

        /// <summary>
        /// **fi:** Pyydetty määrä per sivu | **en:** Requested amount of job postings
        /// </summary>
        /// <value>**fi:** Pyydetty määrä per sivu | **en:** Requested amount of job postings</value>
        [DataMember(Name = "maara", EmitDefaultValue = false)]
        public int Maara { get; set; }

        /// <summary>
        /// **fi:** Sivun numero | **en:** Page number
        /// </summary>
        /// <value>**fi:** Sivun numero | **en:** Page number</value>
        [DataMember(Name = "sivu", EmitDefaultValue = false)]
        public int Sivu { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Sivutus {\n");
            sb.Append("  Maara: ").Append(Maara).Append("\n");
            sb.Append("  Sivu: ").Append(Sivu).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Sivutus);
        }

        /// <summary>
        /// Returns true if Sivutus instances are equal
        /// </summary>
        /// <param name="input">Instance of Sivutus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Sivutus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Maara == input.Maara ||
                    this.Maara.Equals(input.Maara)
                ) && 
                (
                    this.Sivu == input.Sivu ||
                    this.Sivu.Equals(input.Sivu)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Maara.GetHashCode();
                hashCode = (hashCode * 59) + this.Sivu.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
