/*
 * TMT - Työpaikkailmoituksien hakurajapinta | Get Job postings
 *
 * <p>Tämän rajapinnan avulla voit hakea kaikki Työmarkkinatorilla julkaistut työpaikkailmoitukset.</p> <p>With this rest interface, you can retrieve all Job postings published in Job market Finland.</p>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CodeGen.Api.TMT.Client.OpenAPIDateConverter;

namespace CodeGen.Api.TMT.Model
{
    /// <summary>
    /// **fi:** Yrittäjyyden tiedot, jos palvelussuhteen tyyppi on &#39;*04*&#39; | **en:** Information of entrepreneur, if type of relationship is &#39;*04*&#39;
    /// </summary>
    [DataContract(Name = "Yrittajyys")]
    public partial class Yrittajyys : IEquatable<Yrittajyys>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Yrittajyys" /> class.
        /// </summary>
        /// <param name="franchising">**fi:** Franchising | **en:** Franchising.</param>
        /// <param name="franchisingSopimusaika">**fi:** Franchising sopimusaika | **en:**  Franchising contract period.</param>
        /// <param name="omaRahoitusLisatietoja">**fi:** Oma rahoitus lisätietoja | **en:** Additional information for self financing.</param>
        /// <param name="omaRahoitusVaaditaan">**fi:** Oma rahoitusvaaditaan | **en:** Self financing is required.</param>
        public Yrittajyys(bool franchising = default(bool), List<LokalisoituArvo> franchisingSopimusaika = default(List<LokalisoituArvo>), List<LokalisoituArvo> omaRahoitusLisatietoja = default(List<LokalisoituArvo>), bool omaRahoitusVaaditaan = default(bool))
        {
            this.Franchising = franchising;
            this.FranchisingSopimusaika = franchisingSopimusaika;
            this.OmaRahoitusLisatietoja = omaRahoitusLisatietoja;
            this.OmaRahoitusVaaditaan = omaRahoitusVaaditaan;
        }

        /// <summary>
        /// **fi:** Franchising | **en:** Franchising
        /// </summary>
        /// <value>**fi:** Franchising | **en:** Franchising</value>
        [DataMember(Name = "franchising", EmitDefaultValue = true)]
        public bool Franchising { get; set; }

        /// <summary>
        /// **fi:** Franchising sopimusaika | **en:**  Franchising contract period
        /// </summary>
        /// <value>**fi:** Franchising sopimusaika | **en:**  Franchising contract period</value>
        [DataMember(Name = "franchisingSopimusaika", EmitDefaultValue = false)]
        public List<LokalisoituArvo> FranchisingSopimusaika { get; set; }

        /// <summary>
        /// **fi:** Oma rahoitus lisätietoja | **en:** Additional information for self financing
        /// </summary>
        /// <value>**fi:** Oma rahoitus lisätietoja | **en:** Additional information for self financing</value>
        [DataMember(Name = "omaRahoitusLisatietoja", EmitDefaultValue = false)]
        public List<LokalisoituArvo> OmaRahoitusLisatietoja { get; set; }

        /// <summary>
        /// **fi:** Oma rahoitusvaaditaan | **en:** Self financing is required
        /// </summary>
        /// <value>**fi:** Oma rahoitusvaaditaan | **en:** Self financing is required</value>
        [DataMember(Name = "omaRahoitusVaaditaan", EmitDefaultValue = true)]
        public bool OmaRahoitusVaaditaan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Yrittajyys {\n");
            sb.Append("  Franchising: ").Append(Franchising).Append("\n");
            sb.Append("  FranchisingSopimusaika: ").Append(FranchisingSopimusaika).Append("\n");
            sb.Append("  OmaRahoitusLisatietoja: ").Append(OmaRahoitusLisatietoja).Append("\n");
            sb.Append("  OmaRahoitusVaaditaan: ").Append(OmaRahoitusVaaditaan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Yrittajyys);
        }

        /// <summary>
        /// Returns true if Yrittajyys instances are equal
        /// </summary>
        /// <param name="input">Instance of Yrittajyys to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Yrittajyys input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Franchising == input.Franchising ||
                    this.Franchising.Equals(input.Franchising)
                ) && 
                (
                    this.FranchisingSopimusaika == input.FranchisingSopimusaika ||
                    this.FranchisingSopimusaika != null &&
                    input.FranchisingSopimusaika != null &&
                    this.FranchisingSopimusaika.SequenceEqual(input.FranchisingSopimusaika)
                ) && 
                (
                    this.OmaRahoitusLisatietoja == input.OmaRahoitusLisatietoja ||
                    this.OmaRahoitusLisatietoja != null &&
                    input.OmaRahoitusLisatietoja != null &&
                    this.OmaRahoitusLisatietoja.SequenceEqual(input.OmaRahoitusLisatietoja)
                ) && 
                (
                    this.OmaRahoitusVaaditaan == input.OmaRahoitusVaaditaan ||
                    this.OmaRahoitusVaaditaan.Equals(input.OmaRahoitusVaaditaan)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Franchising.GetHashCode();
                if (this.FranchisingSopimusaika != null)
                {
                    hashCode = (hashCode * 59) + this.FranchisingSopimusaika.GetHashCode();
                }
                if (this.OmaRahoitusLisatietoja != null)
                {
                    hashCode = (hashCode * 59) + this.OmaRahoitusLisatietoja.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.OmaRahoitusVaaditaan.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
