openapi: 3.1.0
info:
  title: TMTProductizer
  version: "1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /jobs:
    get:
      summary: Get Jobs
      tags:
        - jobs
      responses: {}
      operationId: get-jobs
      description: Productizer endpoint for retrieving job posting information
  /wake-up:
    get:
      summary: warmup the service
      tags:
        - lambda
      operationId: wake-up
      description: A wake signal handler
components:
  schemas: {}
