name: Build and deploy

on:
  push:
    branches:
      - main

env:
  PULUMI_ORGANIZATION: virtualfinland
  PULUMI_STACK: dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ env.PULUMI_STACK }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish src/TMTProductizer/TMTProductizer.csproj -c Release -o release --nologo
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: /home/runner/work/tmt-productizer/tmt-productizer/release/
          retention-days: 5
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ env.PULUMI_STACK }}
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./deployment/release/
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Pulumi deployment
        uses: pulumi/actions@v3
        with:
          work-dir: ./deployment
          command: up
          stack-name: ${{ env.PULUMI_ORGANIZATION }}/${{ env.PULUMI_STACK }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN}}
