name: Preview Pulumi

on:
  pull_request

env:
  PULUMI_ORGANIZATION: virtualfinland
  PULUMI_STACK: dev

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -o ./deployment/release
      - name: Test
        run: dotnet test ./deployment/release/TMTProductizer.UnitTests.dll --no-build --verbosity normal
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Select Pulumi stack
        working-directory: ./deployment
        run: pulumi stack select ${{ env.PULUMI_ORGANIZATION}}/${{ env.PULUMI_STACK }}
      - name: Set artifact path
        working-directory: ./deployment
        run: pulumi config set artifactPath release/
      - name: Run Pulumi deployment
        working-directory: ./deployment
        run: pulumi preview
